name: MY FILM SITE
favicon: null
layout_spectrum: 0.6618733068462461
typography_spectrum: 0.4736783953849226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4345783921889961
  lightness: 0.035385597962886095
  saturation: 0.713693714234978
  rhythmicContrast: 0.1591022356878966
purpose: []
